# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deplistn',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Bölüm ID')),
                ('dep_name', models.CharField(max_length=512, verbose_name='Program Adı')),
                ('dep_code', models.CharField(max_length=32, verbose_name='Program Kodu')),
                ('dep_note', models.CharField(max_length=256, null=True, verbose_name='Program Açıklaması')),
                ('dep_duration', models.SmallIntegerField(verbose_name='Öğretim Süresi')),
                ('dep_point_type', models.CharField(max_length=16, verbose_name='Puan Türü')),
                ('dep_limit', models.IntegerField(null=True, verbose_name='Genel Kontenjan')),
                ('dep_point16', models.CharField(blank=True, max_length=64, null=True, verbose_name='2016 ÖSYS Taban Puanı')),
                ('dep_placement16', models.IntegerField(null=True, verbose_name='2016 ÖSYS Yerleştirme Sırası')),
                ('dep_rules', models.CharField(max_length=64, null=True, verbose_name='Özel Koşul')),
                ('dep_dig', models.IntegerField(null=True, verbose_name='Program Grup')),
            ],
        ),
        migrations.CreateModel(
            name='Faklist',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Fakülte ID')),
                ('fak_name', models.CharField(max_length=512, verbose_name='Fakülte Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Unilist',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('uni_name', models.CharField(max_length=512, verbose_name='Üniversite Adı')),
                ('uni_city', models.CharField(max_length=128, verbose_name='Üniversitenin Bulunduğu Şehir')),
                ('uni_type', models.CharField(max_length=64, verbose_name='Üniversite Tipi')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=256, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='faklist',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Unilist'),
        ),
        migrations.AddField(
            model_name='deplistn',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Faklist'),
        ),
        migrations.AddField(
            model_name='deplistn',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Unilist'),
        ),
    ]
