# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deplist',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Bölüm ID')),
                ('dep_name', models.CharField(max_length=512, verbose_name='Program Adı')),
                ('dep_code', models.CharField(max_length=32, verbose_name='Program Kodu')),
                ('dep_note', models.CharField(max_length=256, null=True, verbose_name='Program Açıklaması')),
                ('dep_duration', models.SmallIntegerField(verbose_name='Öğretim Süresi')),
                ('dep_point_type', models.CharField(max_length=16, verbose_name='Puan Türü')),
                ('dep_limit', models.IntegerField(null=True, verbose_name='Genel Kontenjan')),
                ('dep_point16', models.CharField(blank=True, max_length=64, null=True, verbose_name='2016 ÖSYS Taban Puanı')),
                ('dep_placement16', models.CharField(max_length=16, null=True, verbose_name='2016 ÖSYS Yerleştirme Sırası')),
                ('dep_rules', models.CharField(max_length=64, null=True, verbose_name='Özel Koşul')),
                ('dep_dig', models.IntegerField(null=True, verbose_name='Program Grup')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Faklist')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Unilist')),
            ],
        ),
        migrations.RemoveField(
            model_name='deplistn',
            name='fid',
        ),
        migrations.RemoveField(
            model_name='deplistn',
            name='uid',
        ),
        migrations.DeleteModel(
            name='Deplistn',
        ),
    ]
